### ISSUE TITLE
No module named 'ppgs.config'

### ISSUE THREAD

**Issue by Cheneng** [interactiveaudiolab/ppgs#11]
import ppgs
raise ModuleNotFoundError: No module named 'ppgs.config'

After using 
`pip install ppgs`

**Comment by maxrmorrison** [comment]
Thanks for catching that. Fixed in [657fafc](https://github.com/interactiveaudiolab/ppgs/commit/657fafc2320cd7fe194209a331c6a8065d893b94) and deployed in version 0.0.3.
