### ISSUE TITLE
where dose the balanced_similarity.pt come from?

### ISSUE THREAD

**Issue by Lindsay284** [interactiveaudiolab/ppgs#14]
In ppgs.assets, there are balanced_similarity.pt, I'm wondering how this .pt file was computed? BTW, for the phoneme_weights.pt, I have the same question. Thank you for your answering!!

**Comment by maxrmorrison** [comment]
The similarity matrix was computed [here](https://github.com/interactiveaudiolab/ppgs/blob/09af034fc87e14e59cee7908596fc8edf9a4d06b/ppgs/evaluate/metrics.py#L301). We used the config `config/balanced.py` to train the corresponding model. Phoneme weight computation is done [here](https://github.com/interactiveaudiolab/ppgs/blob/09af034fc87e14e59cee7908596fc8edf9a4d06b/ppgs/load.py#L90).
